# Generated by Django 3.2.21 on 2023-10-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_technical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='technical',
            field=models.BooleanField(default=False, verbose_name='Technical Section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='warehouse_keeper',
            field=models.BooleanField(default=False, verbose_name='warehouse_keeper'),
        ),
    ]
