# Generated by Django 3.2.21 on 2023-10-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231005_0006'),
        ('warehouse', '0004_auto_20231003_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='date',
            field=models.DateField(blank=True, verbose_name='Approved Date'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='number',
            field=models.CharField(max_length=200, verbose_name='MR Number'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mr', to='warehouse.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='mritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mritems', to='warehouse.item', verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='mritem',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Item Number'),
        ),
        migrations.AlterField(
            model_name='mritem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='mritem',
            name='tag_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='MESC Number'),
        ),
        migrations.AlterField(
            model_name='mritem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='warehouse.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='date',
            field=models.DateField(blank=True, verbose_name='Sent Date'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='mr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls', to='warehouse.materialrequisition', verbose_name='MR Number'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='number',
            field=models.CharField(max_length=200, verbose_name='Packing List Number'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls', to='warehouse.procurementorder', verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pls', to='warehouse.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='plitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plitems', to='warehouse.item', verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='plitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='plitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plitems', to='warehouse.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poitems', to='warehouse.item', verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poitems', to='warehouse.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Seller (Company Name)'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='date',
            field=models.DateField(blank=True, verbose_name='Date Confirmed'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='mr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='warehouse.materialrequisition', verbose_name='MR Number'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='number',
            field=models.CharField(max_length=200, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='warehouse.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(max_length=40, verbose_name='Project Number'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='abrv',
            field=models.CharField(max_length=10, verbose_name='Abriviation'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Unit Name'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='core.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'warehouse_keeper': True}, to='core.User', verbose_name='Warehouse Keepers'),
        ),
    ]
