# Generated by Django 3.2.21 on 2023-10-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231005_0006'),
        ('warehouse', '0006_condition_materialreceiptsheet_mrsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'warehouse_keeper': True}, related_name='whs', to='core.User', verbose_name='Warehouse Keepers'),
        ),
    ]
