# Generated by Django 3.2.21 on 2023-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='total_in_all',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='total_in_all'),
        ),
    ]
