# Generated by Django 3.2.21 on 2023-10-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231005_0006'),
        ('warehouse', '0010_alter_inventoryitem_total_in_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='MIR Number')),
                ('issue_date', models.DateField(blank=True, verbose_name='Issue Date')),
                ('required_date', models.DateField(blank=True, verbose_name='Required Date')),
                ('client_department', models.CharField(max_length=100, verbose_name='Client Department')),
                ('sent_to_warehouse', models.BooleanField(default=False, verbose_name='sent to warehouse')),
                ('sent_to_location', models.BooleanField(default=False, verbose_name='sent to location')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mir', to='core.user', verbose_name='ثبت شده توسط')),
                ('mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mir', to='warehouse.materialrequisition', verbose_name='MR Number')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mir', to='warehouse.packinglist', verbose_name='Packing List Number')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mir', to='warehouse.procurementorder', verbose_name='PO Number')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mir', to='warehouse.project', verbose_name='Project')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mir', to='warehouse.warehouse', verbose_name='Origin(From)')),
            ],
            options={
                'verbose_name': 'Material Issue Request',
                'verbose_name_plural': 'Material Issue Requests',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MIRItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Mr Item No.')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='remakrs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miritems', to='warehouse.item', verbose_name='Item Description')),
                ('mir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.materialissuerequest')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miritems', to='warehouse.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'MIR Item',
                'verbose_name_plural': 'MIR Items',
            },
        ),
    ]
