# Generated by Django 3.2.21 on 2023-10-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_materialissuerequest_miritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ivitems', to='warehouse.condition', verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='miritem',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='miritems', to='warehouse.condition', verbose_name='Condition'),
        ),
    ]
