# Generated by Django 3.2.21 on 2023-10-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequisition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mr', to='warehouse.category', verbose_name='category'),
        ),
    ]
