# Generated by Django 3.2.21 on 2023-10-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231005_0006'),
        ('warehouse', '0015_materialrequisition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.user', verbose_name='ثبت شده توسط'),
        ),
    ]
