# Generated by Django 3.2.21 on 2023-10-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_cluster_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='mritem',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.cluster', verbose_name='cluster'),
        ),
        migrations.AddField(
            model_name='mritem',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.pipeline', verbose_name='pipe line'),
        ),
    ]
