# Generated by Django 3.2.21 on 2023-10-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_auto_20231012_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poitems', to='warehouse.cluster', verbose_name='cluster'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poitems', to='warehouse.pipeline', verbose_name='pipe line'),
        ),
    ]
