# Generated by Django 3.2.21 on 2023-10-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_auto_20231013_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mritem',
            name='tag_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Size'),
        ),
    ]
